// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tblogmnlaeeamnanksys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRibG9nbW5sYWVlYW1uYW5rc3lzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MTAwNzQsImV4cCI6MjA2NTk4NjA3NH0.uqpwnZbgnUnsrdNGhxfmQij7DrmOrzFVLcVOwqalfGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);